services:
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./Frontend:/app
    ports:
      - "5172:5172"
    command: sh -c "npm install && npm run dev"

  backend:
    image: node:18
    working_dir: /app
    volumes:
      - ./Backend:/app
    ports:
      - "5173:3000"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - mongo
    env_file:
      - ./Backend/.env.development

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "5170:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
